### ISSUE TITLE
All messages start with cyan.msg and whatever after it

### ISSUE THREAD

**Issue by Galabeam** [Aeldit/Cyan#7]
**Describe the bug**
When any message is displayed, it shows the code message instead.

**Your version**
Minecraft 1.20
Cyan 0.9.11

**To Reproduce**

1. Go to the chat
2. Type in /cyan getConfig
3. The messages appear in a code format

**Expected behavior**
The command would show the state of the configs properly.

**Screenshots**
![Screenshot 2023-07-27 191858](https://github.com/Aeldit/Cyan/assets/68124962/334d84fb-5b45-4240-a910-3b4925aeecad)

**Comment by Aeldit** [comment]
Is the option useCustomTranslations ON or OFF ? And are you playing in solo or is the mod on a server?

**Comment by Galabeam** [comment]
Thank you, I didn't realize that was off, and yes that was the reason I just had the custom translations off.

**Comment by Aeldit** [comment]
Nice 👌 (also I'm glad it wasn't a bug given the time I spend on searching for bugs 😅)
