### ISSUE TITLE
Unable to start server on 1.21 

### ISSUE THREAD

**Issue by PixelPacker** [Aeldit/Cyan#8]
Here is my log file, only mods is Cyan and the required lib files.
[latest.log](https://github.com/user-attachments/files/15827744/latest.log)

**Comment by Aeldit** [comment]
This should be fixed by [7864569](https://github.com/Aeldit/Cyan/commit/7864569ebc091338d228a7968c4682239b9beeda), can you confirm ? (It works on my end but it is to be sure)
